### PR TITLE
Adding org-wide templates

### PR DESCRIPTION
**Pull request by greglucas**
Copied some of the contents over from imap_processing. I also added a new L5 issue template. If you go to view the file directly in the PR it should render how you would see it when opening an issue.

### CODE REVIEW

**Comment by greglucas** [comment]
See here for examples of other files we can add later: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Review by sdhoyt — APPROVED** [review]
Looks good!

**Comment by greglucas** [comment]
Merging now just to put it in and see how it works. @bourque, I encourage you to keep iterating here and adding to this repo so we get your nice content org-wide!

**Comment by bourque** [comment]
Neat! I didn't know you could do this.

**Pull request merged**
